disable-all = true

[linters]
  enable = ["gofmt", "goimports", "gocyclo", "errcheck", "staticcheck", "misspell", "gosec", "funlen", "lll", "dupl"]

[linters-settings]
  [linters-settings.golint]
    min-confidence = 0.3
  [linters-settings.gocyclo]
    min-complexity = 20
  [linters-settings.dupl]
    threshold = 200
  [linters-settings.lll]
    line-length = 120
  [linters-settings.funlen]
    statements = 100
    lines = 100
  [linters-settings.errcheck]
    asserts = false

[output]
  format = "tab"

[skip-dirs]
  ["vendor/"]

[skip-files]
  ["_easyjson.go", ".pb.go", ".svc.go"]

modules-download-mode = "readonly"
