name: auth-service-otel

services:
  otel-collector:
      image: otel/opentelemetry-collector-contrib:latest
      command: ["--config=/etc/otel-collector.yml"]
      volumes:
        - ./otel-collector.yml:/etc/otel-collector-config.yml
      ports:
        - "4317:4317"   
        - "4318:4318"   
        - "9464:9464"  

  jaeger:
      image: jaegertracing/all-in-one:latest
      environment:
        - COLLECTOR_ZIPKIN_HTTP_PORT=9411
        - COLLECTOR_OTLP_ENABLED=true
      ports:
        - "16686:16686" 
        - "14250:14250"  
        - "14268:14268"
        - "14269:14269"
        - "4317:4317"   
        - "4318:4318"  

        